### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by drwulsen** [Wintermute0110/repository.wintermute0110#2]
Hi there,

I'm trying to run my system (x86_64) entirely on Python 3 (3.7 at the moment).
I've managed to get kodi to run; all other stuff that is installed works well.
Python 2 should be phased out until end of 2020, at least that's what is being discussed on the kodi page; so the transition to Python3 is on the way.

That's what I get without Python2 installed:
```
2020-01-01 19:34:38.164 T:29699   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ModuleNotFoundError'>
                                            Error Contents: No module named 'urllib2'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/addon.py", line 21, in <module>
                                                import resources.main as main
                                              File "/home/kodi/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/main.py", line 20, in <module>
                                                import re, urllib, urllib2, urlparse, socket, exceptions, hashlib
                                            ModuleNotFoundError: No module named 'urllib2'
                                            -->End of Python script error report<--
```

I'm not able to guess how much work it will take to rewrite the plugin;
nor do I know if it's on the roadmap either.

Could you please give some info on what is planned?
Thanks!!

**Comment by Wintermute0110** [comment]
Python 3 support in AEL/AML is intended since its inception about 4 years ago. If you like technical details, the code uses `from __future__` and similar stuff where possible. This means that the changes to start using Python 3 are minimal, however some changes are required.

The current plan is to start supporting Python 3 when Matrix reaches the release candidate stage. Soon after Matrix RC1 is released I will release AEL/AML versions supporting Python 3. There will be no parallel development of Python 2/3 versions.

**Comment by drwulsen** [comment]
Thank you very much for the info!
It's nice to hear that AEL/AML will be functional even under Matrix and Python3.
For me it's one of the best plugins available - thank you for your good work and effort!
