### ISSUE TITLE
Can this be converted to an installable repository?

### ISSUE THREAD

**Issue by treymerkley** [Wintermute0110/repository.wintermute0110#3]
You have all of your package releases here, but no XML files so I can download this as-is and install it as a repository. Can you make a repository that can be installed in Kodi?

**Comment by Wintermute0110** [comment]
Hi. This is done on purpose. Usually upgrading AEL involves some upgrade process that is not automatic. If I implement the changes you propose AEL will upgrade automatically and it will stop working. I prefer users to go to the forum and install new versions of AEL manually after reading the release notes and the upgrade process.

I guess once I am happy with the AEL database, including all metadata and supported artwork types, then it will be time for automatic AEL upgrades. In other words, once the AEL games database is stable.

**Comment by treymerkley** [comment]
Hey, makes sense. Thanks!
